CREATE TABLE students_name
(STUDENT_ID SERIAL PRIMARY KEY NOT NULL, NAME TEXT);

CREATE TABLE data
(DATA_ID SERIAL PRIMARY KEY NOT NULL,
TELEGRAM_ID BIGINT NOT NULL UNIQUE,
BIRTHDATE TEXT NOT NULL,
START_DATE TEXT NOT NULL);

CREATE TABLE styles
(STYLE_ID SERIAL PRIMARY KEY NOT NULL,
STYLE TEXT NOT NULL);

CREATE TABLE levels
(LEVEL_ID SERIAL PRIMARY KEY NOT NULL,
LEVEL TEXT NOT NULL);

CREATE TABLE common_info
(INFO_ID SERIAL PRIMARY KEY NOT NULL,
STUDENT_ID INT REFERENCES students_name (STUDENT_ID),
DATA_ID INT REFERENCES data (DATA_ID),
STYLE_ID INT REFERENCES styles (STYLE_ID),
LEVEL_ID INT REFERENCES levels (LEVEL_ID));
