CREATE TABLE menu(

MENU_ID SERIAL PRIMARY KEY NOT NULL,
MAIN_CODE VARCHAR(20),
MAIN_NAME VARCHAR(30),

CATEGORY_CODE VARCHAR(20),
CATEGORY_NAME VARCHAR(30),

SUBCATEGORY_CODE VARCHAR(20),
SUBCATEGORY_NAME VARCHAR(30),

TEXT TEXT,
PHOTO VARCHAR(250)

);