CREATE TABLE students_name
(STUDENT_ID SERIAL PRIMARY KEY NOT NULL,
NAME TEXT,
DATA_ID SERIAL);

CREATE TABLE data
(DATA_ID SERIAL PRIMARY KEY NOT NULL,
TELEGRAM_ID BIGINT NOT NULL UNIQUE,
BIRTHDATE TEXT NOT NULL,
START_DATE TEXT NOT NULL,
STYLE_ID SERIAL);

CREATE TABLE styles
(STYLE_ID SERIAL PRIMARY KEY NOT NULL,
STYLE TEXT NOT NULL,
LEVEL_ID SERIAL);

CREATE TABLE levels
(LEVEL_ID SERIAL PRIMARY KEY NOT NULL,
LEVEL TEXT NOT NULL);

